# Generated by Django 4.2 on 2025-10-31 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0004_book_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='plagiat_local',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='book',
            name='plagiat_web',
            field=models.BooleanField(default=False),
        ),
    ]
