# Generated by Django 4.2 on 2025-10-28 01:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('book', '0004_book_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='collaborators',
            field=models.ManyToManyField(blank=True, related_name='collaborative_books', to=settings.AUTH_USER_MODEL),
        ),
    ]
