# Generated by Django 4.2 on 2025-10-31 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0005_book_collaborators'),
        ('book', '0005_book_plagiat_local_book_plagiat_web'),
    ]

    operations = [
    ]
