# Generated by Django 4.2 on 2025-10-31 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0006_book_favorites'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='genre',
            field=models.CharField(choices=[('romance', 'Romance'), ('fantasy', 'Fantasy'), ('thriller', 'Thriller'), ('science_fiction', 'Science-Fiction'), ('aventure', 'Aventure'), ('horreur', 'Horreur'), ('drame', 'Drame'), ('historique', 'Historique'), ('poesie', 'Poésie'), ('biographie', 'Biographie'), ('developpement_personnel', 'Développement personnel'), ('jeunesse', 'Jeunesse'), ('fanfiction', 'Fanfiction'), ('dark_romance', 'Dark Romance'), ('autre', 'Autre')], max_length=100),
        ),
    ]
