# Generated by Django 4.2 on 2025-11-01 01:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0006_merge_20251031_2112'),
        ('book', '0007_alter_book_genre'),
    ]

    operations = [
    ]
