# Generated by Django 4.2 on 2025-10-31 15:55

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0007_alter_book_genre'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('booksRecommendation', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userinteraction',
            unique_together={('user', 'book')},
        ),
    ]
