# Generated by Django 4.2 on 2025-10-31 17:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('book', '0004_book_content'),
        ('badge', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='badge',
            name='users',
        ),
        migrations.AddField(
            model_name='badge',
            name='condition_params',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='badge',
            name='condition_type',
            field=models.CharField(choices=[('plagiat_check', 'Vérification Plagiat'), ('books_completed', 'Livres Terminés'), ('books_count', 'Nombre de Livres'), ('forum_posts', 'Posts Forum'), ('words_written', 'Mots Écrits'), ('custom', 'Condition Personnalisée')], default=50, max_length=50),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('book_created', 'Livre Créé'), ('book_completed', 'Livre Terminé'), ('plagiat_check_done', 'Vérification Plagiat Effectuée'), ('plagiat_web_detected', 'Plagiat Web Détecté'), ('plagiat_detected', 'Plagiat Détecté'), ('no_plagiat', 'Aucun Plagiat'), ('forum_post_created', 'Post Forum Créé'), ('chapter_added', 'Chapitre Ajouté')], max_length=50)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('book', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to='book.book')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserBadge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_unlocked', models.BooleanField(default=False)),
                ('unlocked_at', models.DateTimeField(blank=True, null=True)),
                ('badge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_badges', to='badge.badge')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_badges', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-unlocked_at'],
                'unique_together': {('user', 'badge')},
            },
        ),
        migrations.AddIndex(
            model_name='activitylog',
            index=models.Index(fields=['user', 'action_type'], name='badge_activ_user_id_65db23_idx'),
        ),
        migrations.AddIndex(
            model_name='activitylog',
            index=models.Index(fields=['created_at'], name='badge_activ_created_4c53d5_idx'),
        ),
    ]
