# Generated by Django 4.2 on 2025-10-31 18:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('badge', '0002_remove_badge_users_badge_condition_params_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userbadge',
            options={},
        ),
        migrations.RenameField(
            model_name='userbadge',
            old_name='is_unlocked',
            new_name='unlocked',
        ),
        migrations.RemoveField(
            model_name='badge',
            name='condition_params',
        ),
        migrations.RemoveField(
            model_name='badge',
            name='condition_type',
        ),
        migrations.AddField(
            model_name='badge',
            name='badge_type',
            field=models.CharField(choices=[('plagiat', 'Vérification Plagiat'), ('first_book', 'Premier Livre'), ('completed_books', 'Livres Terminés'), ('custom', 'Personnalisé')], default='custom', max_length=50),
        ),
        migrations.AddField(
            model_name='badge',
            name='condition_value',
            field=models.IntegerField(default=0, help_text='Valeur requise (ex: nombre de livres)'),
        ),
        migrations.AlterField(
            model_name='userbadge',
            name='badge',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='badge.badge'),
        ),
        migrations.DeleteModel(
            name='ActivityLog',
        ),
    ]
